__1.__ Установите, какие произведения матриц $AB$ и $BA$ определены, и найдите размерности полученных матриц:

   а) $A$ — матрица $4\times 2$, $B$ — матрица $4\times 2$;
    
   б) $A$ — матрица $2\times 5$, $B$ — матрица $5\times 3$;
    
   в) $A$ — матрица $8\times 3$, $B$ — матрица $3\times 8$;
    
   г) $A$ — квадратная матрица $4\times 4$, $B$ — квадратная матрица $4\times 4$.

Ответ:

а) АхВ перемножить нельзя (4х2)и(4х2);

б) АхВ (2х3); ВхА перемножить нельзя (5х3)и(2х5);

в) АхВ (8х8); ВхА (3х3);

г) АхВ/ВхА (4х4).

__2.__ Найдите сумму и произведение матриц $A=\begin{pmatrix}
1 & -2\\ 
3 & 0
\end{pmatrix}$ и $B=\begin{pmatrix}
4 & -1\\ 
0 & 5
\end{pmatrix}.$

$A+В=\begin{pmatrix}
1+4 & -2-1\\ 
3+0 & 0+5
\end{pmatrix}$ = $\begin{pmatrix}
5 & -3\\ 
3 & 5
\end{pmatrix}.$

$A*В=\begin{pmatrix}
1*4+-2*0 & 1*-1+-2*5\\ 
3*4+0*0 & 3*-1+0*5
\end{pmatrix}$ = $\begin{pmatrix}
4 & -11\\ 
12 & -3
\end{pmatrix}.$

$В*А=\begin{pmatrix}
4*1+-1*3 & 4*-2+-1*0\\ 
0*1+5*3 & 0*-2+5*0
\end{pmatrix}$ = $\begin{pmatrix}
1 & -8\\ 
15 & 0
\end{pmatrix}.$

In [7]:
import numpy as np
A = np.array([[1, -2], [3, 0]])
B = np.array([[4, -1], [0, 5]])
print(f'A+B\n{A+B}, \nA*B\n{np.dot(A, B)}, \nB*A\n{np.dot(B, A)}')

A+B
[[ 5 -3]
 [ 3  5]], 
A*B
[[  4 -11]
 [ 12  -3]], 
B*A
[[ 1 -8]
 [15  0]]


__3.__ Из закономерностей сложения и умножения матриц на число можно сделать вывод, что матрицы одного размера образуют линейное пространство. Вычислите линейную комбинацию $3A-2B+4C$ для матриц $A=\begin{pmatrix}
1 & 7\\ 
3 & -6
\end{pmatrix}$, $B=\begin{pmatrix}
0 & 5\\ 
2 & -1
\end{pmatrix}$, $C=\begin{pmatrix}
2 & -4\\ 
1 & 1
\end{pmatrix}.$

$3A-2B+4C=\begin{pmatrix}
3*1-2*0+4*2 & 3*7-2*5+4*-4\\ 
3*3-2*2+4*1 & 3*-6-2*-1+4*1
\end{pmatrix}$ = $\begin{pmatrix}
11 & -5\\ 
9 & -12
\end{pmatrix}.$

In [15]:
A = np.array([[1, 7], [3, -6]])
B = np.array([[0, 5], [2, -1]])
C = np.array([[2, -4], [1, 1]])
print(f'3𝐴−2𝐵+4𝐶\n{3*𝐴-2*𝐵+4*𝐶}')

3𝐴−2𝐵+4𝐶
[[ 11  -5]
 [  9 -12]]


__4.__ Дана матрица $A=\begin{pmatrix}
4 & 1\\ 
5 & -2\\ 
2 & 3
\end{pmatrix}$.
Вычислите $AA^{T}$ и $A^{T}A$.

In [18]:
A = np.array([[4, 1], [5, -2], [2, 3]])
print(f'𝐴*𝐴𝑇\n{np.dot(A, A.T)},\n𝐴𝑇*A\n{np.dot(A.T, A)}')

𝐴*𝐴𝑇
[[17 18 11]
 [18 29  4]
 [11  4 13]],
𝐴𝑇*A
[[45  0]
 [ 0 14]]


__1.__ Вычислите определитель:

   a)

$$\begin{vmatrix}
sinx & -cosx\\ 
cosx & sinx
\end{vmatrix};$$

   б)
    
$$\begin{vmatrix}
4 & 2 & 3\\ 
0 & 5 & 1\\ 
0 & 0 & 9
\end{vmatrix};$$
    
   в)

$$\begin{vmatrix}
1 & 2 & 3\\ 
4 & 5 & 6\\ 
7 & 8 & 9
\end{vmatrix}.$$

a) $sin^2(x)+cos^2(x)=1$

б) 4 * 5 * 9 = 180

в) 7 * (12-15) - 8 * (6-12) + 9 * (5-8) = 0

__2.__ Определитель матрицы $A$ равен $4$. Найдите:

   а) $det(A^{2})$;
    
   б) $det(A^{T})$;
    
   в) $det(2A)$.

   а) $det(A^{2})$ = 16;
    
   б) $det(A^{T})=det(A)=4$;
    
   в) $det(2A)=2^n det(A)=4*2^n$.

__3.__  Докажите, что матрица:

$$\begin{pmatrix}
-2 & 7 & -3\\ 
4 & -14 & 6\\ 
-3 & 7 & 13
\end{pmatrix}$$
   
вырожденная.

Строки 1 и 2 - линейно зависимые: i1 = i2 / -2

__4.__ Найдите ранг матрицы:

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
1 & 1 & 1\\ 
2 & 3 & 4
\end{pmatrix};$

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 2 & 2\\ 
0 & 0 & 4 & 3\\ 
2 & 3 & 5 & 6
\end{pmatrix}.$

   а) $\begin{pmatrix}
1 & 2 & 3\\ 
0 & -1 & -2\\ 
0 & -1 & -2
\end{pmatrix}$
// Определитель - 2

   б) $\begin{pmatrix}
0 & 0 & 2 & 1\\ 
0 & 0 & 0 & 1\\ 
0 & 0 & 0 & 0\\ 
2 & 3 & 5 & 6
\end{pmatrix}$
// Определитель - 3