__1.__ Найдите собственные векторы и собственные значения для линейного оператора, заданного матрицей:

$$A=\begin{pmatrix}
-1 & -6\\ 
2 & 6
\end{pmatrix}.$$

In [2]:
import numpy as np
a = np.array([[-1, -6], [2, 6]])
w, v = np.linalg.eig(a)

In [3]:
print ("Собственные числа:\n", w)
print ("Собственные векторы:\n", v)

Собственные числа:
 [2. 3.]
Собственные векторы:
 [[-0.89442719  0.83205029]
 [ 0.4472136  -0.5547002 ]]


__2.__ Дан оператор поворота на 180 градусов, задаваемый матрицей:

$$A=\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}.$$

Покажите, что __любой__ вектор считается для него собственным.

In [9]:
b = np.array([[-1, 0], [0, -1]])
n, m = np.linalg.eig(b)

In [10]:
print ("Собственные числа:\n", n)
print ("Собственные векторы:\n", m)

Собственные числа:
 [-1. -1.]
Собственные векторы:
 [[1. 0.]
 [0. 1.]]


$$\begin{pmatrix}
-1 & 0\\ 
0 & -1
\end{pmatrix}
\begin{pmatrix}
x_1\\
x_2\end{pmatrix}=\lambda\begin{pmatrix}
x_1\\
x_2\end{pmatrix}$$

$$
\left\{
    \begin{array}\\
        -x_1 = \lambda \cdot x_1 \\
        -x_2 = \lambda \cdot x_2
    \end{array}
\right.
$$
Посдтавим собственные значения
$$
\lambda_1 = \lambda_2 = -1
$$
Получим:
$$
\left\{
    \begin{array}\\
        -x_1 = -x_1 \\
        -x_2 = -x_2
    \end{array}
\right.
$$
Любое значение, подставленное в систему уравнений - верное

__3.__ Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}.$$

Установите, считается ли вектор $x=(1,1)$ собственным вектором этого линейного оператора.

In [16]:
c = np.array([[1, 1], [-1, 3]])
f, g = np.linalg.eig(c)

In [17]:
print ("Собственные числа:\n", f)
print ("Собственные векторы:\n", g)

Собственные числа:
 [2.00000002 1.99999998]
Собственные векторы:
 [[ 0.70710677 -0.70710679]
 [ 0.70710679 -0.70710677]]


$$\begin{pmatrix}
1 & 1\\ 
-1 & 3
\end{pmatrix}
\begin{pmatrix}
1\\
1\end{pmatrix}=\lambda\begin{pmatrix}
1\\
1\end{pmatrix}$$

$$
\left\{
    \begin{array}\\
       1+1 = 1\cdot\lambda \\
        -1+3 = 1\cdot\lambda
    \end{array}
\right.
$$
$$
\left\{
    \begin{array}\\
      \lambda = 2\\
      \lambda = 2
    \end{array}
\right.
$$
Вектор х = (1;1) - собственный

**4*.** Пусть линейный оператор задан матрицей:

$$A=\begin{pmatrix} 0 & 3 & 0\\ 3 & 0 & 0\\ 0 & 0 & 3 \end{pmatrix}.$$

Установите, считается ли вектор $x=(3, -3, -4)$ собственным вектором этого линейного оператора.

In [20]:
j = np.array([[0, 3, 0], [3, 0, 0], [0, 0, 3]])
k, l = np.linalg.eig(j)

In [21]:
print ("Собственные числа:\n", k)
print ("Собственные векторы:\n", l)

Собственные числа:
 [ 3. -3.  3.]
Собственные векторы:
 [[ 0.70710678 -0.70710678  0.        ]
 [ 0.70710678  0.70710678  0.        ]
 [ 0.          0.          1.        ]]


$$\begin{pmatrix}
0 & 3 & 0\\ 
3 & 0 & 0\\
0 & 0 & 3
\end{pmatrix}
\begin{pmatrix}
3\\
-3\\
-4
\end{pmatrix}=\lambda\begin{pmatrix}
3\\
-3\\
-4\end{pmatrix}$$

$$
\left\{
    \begin{array}\\
       -9 = 3\cdot\lambda \\
       9 = -3\cdot\lambda \\
       -12 = -4\cdot\lambda \\
    \end{array}
\right.
$$
$$
\left\{
    \begin{array}\\
      \lambda = -3\\
      \lambda = -3\\
      \lambda = 3
    \end{array}
\right.
$$
Вектор х = (3;-3;-4) - не является собственным